export const STYLE_OPTIONS = [
  {
    id: "style1",
    label: "Style 1",
    themeClass: "theme-amber",
    layout: "sidebar",
    headerHeightClassName: "h-[60px]",
    headerPaddingClassName: "px-[34px]",
    headerShellClassName: "header-shell-amber-primary",
    navGapClassName: "gap-7",
    navTextClassName: "text-[14px]",
    navUnderlineWidthClassName: "w-5",
    headerRightGapClassName: "gap-[14px]",
    sidebarGridClassName: "sidebar-grid-wide",
    sidebarStackClassName: "gap-6",
    dropdownOpenByDefault: true,
    heroClassName: "sidebar-hero-shell sidebar-hero-amber rounded-[22px]",
    dotsVariant: "sidebar",
    searchVariant: "plain",
    searchFieldHeightClassName: "h-12",
    gridClassName: "gap-5",
    cardTone: "card-tone-amber",
    tabsTone: "tabs-tone-amber",
  },
  {
    id: "style2",
    label: "Style 2",
    themeClass: "theme-cobalt",
    layout: "sidebar",
    headerHeightClassName: "h-[60px]",
    headerPaddingClassName: "px-[34px]",
    headerShellClassName: "header-shell-cobalt-sidebar",
    navGapClassName: "gap-7",
    navTextClassName: "text-[14px]",
    navUnderlineWidthClassName: "w-5",
    headerRightGapClassName: "gap-[14px]",
    sidebarGridClassName: "sidebar-grid-wide",
    sidebarStackClassName: "gap-6",
    dropdownOpenByDefault: false,
    heroClassName: "sidebar-hero-shell sidebar-hero-cobalt rounded-[18px]",
    dotsVariant: "sidebar-compact",
    searchVariant: "filter",
    searchFieldHeightClassName: "h-12",
    gridClassName: "gap-5",
    cardTone: "card-tone-cobalt",
    tabsTone: "tabs-tone-cobalt",
  },
  {
    id: "style-h",
    label: "Style 3",
    themeClass: "theme-amber",
    layout: "hero",
    headerHeightClassName: "h-[60px]",
    headerPaddingClassName: "px-[34px]",
    headerShellClassName: "header-shell-amber-ribbon",
    navGapClassName: "gap-7",
    navTextClassName: "text-[14px]",
    navUnderlineWidthClassName: "w-5",
    headerRightGapClassName: "gap-[14px]",
    dropdownOpenByDefault: false,
    heroClassName: "ribbon-shell ribbon-amber",
    heroWidthClassName: "hero-width-80vw",
    contentWidthClassName: "hero-content-max-80vw",
    heroLayoutClassName: "hero-layout-refined",
    dotsVariant: "hero",
    searchVariant: "compact",
    searchFieldHeightClassName: "h-10",
    gridClassName: "gap-5",
    cardTone: "card-tone-amber",
    tabsTone: "tabs-tone-amber",
  },
  {
    id: "style-2-h",
    label: "Style 4",
    themeClass: "theme-cobalt",
    layout: "hero",
    headerHeightClassName: "h-[60px]",
    headerPaddingClassName: "px-[34px]",
    headerShellClassName: "header-shell-cobalt-ribbon",
    navGapClassName: "gap-7",
    navTextClassName: "text-[14px]",
    navUnderlineWidthClassName: "w-5",
    headerRightGapClassName: "gap-[14px]",
    dropdownOpenByDefault: false,
    heroClassName: "ribbon-shell ribbon-cobalt",
    heroWidthClassName: "hero-width-80vw",
    contentWidthClassName: "hero-content-max-80vw",
    heroLayoutClassName: "hero-layout-refined",
    dotsVariant: "hero",
    searchVariant: "compact",
    searchFieldHeightClassName: "h-10",
    gridClassName: "gap-4",
    cardTone: "card-tone-cobalt",
    tabsTone: "tabs-tone-cobalt",
  },
];

export const NAV_ITEMS = ["首頁", "我的預測", "錢包"];

export const HERO_TABS = [
  "全部",
  "體育",
  "金融",
  "經濟",
  "流行文化",
  "政治",
  "科學",
  "人工智慧",
  "地緣政治",
  "加密貨幣",
];

export const SIDEBAR_ITEMS = [
  { id: "all", label: "全部", icon: "grid", active: true },
  { id: "btc", label: "5分鐘 BTC", icon: "zap", tone: "signal" },
  { id: "sports", label: "體育", icon: "chevron", count: "1420" },
  { id: "finance", label: "金融", icon: "banknote", count: "985" },
  { id: "economy", label: "經濟", icon: "chart", count: "982" },
  { id: "culture", label: "流行文化", icon: "star", count: "861" },
  { id: "politics", label: "政治", icon: "landmark", count: "799" },
  { id: "science", label: "科學", icon: "flask", count: "641" },
  { id: "ai", label: "人工智慧", icon: "cpu", count: "484" },
  { id: "geopolitics", label: "地緣政治", icon: "globe", count: "323" },
  { id: "crypto", label: "加密貨幣", icon: "bitcoin", count: "245" },
  { id: "hot", label: "熱門", icon: "trending-up", count: "127" },
];

export const HERO_SLIDES = [
  {
    id: "tsa",
    hotLabel: "熱門",
    category: "政治",
    title: "3 月 24 日的 TSA 乘客總數是否在 2,800,000 到 3,000,000 之間?",
    yes: 6,
    no: 94,
    yesBarClass: "w-[80px]",
    noBarClass: "flex-1",
    volume: "$4.3M",
    traders: "8.4k",
    resolution: "3 月 24 日內",
    imageUrl:
      "https://images.unsplash.com/photo-1763854413165-1713bc5a7f4a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzQyNTAyMzB8&ixlib=rb-4.1.0&q=80&w=1080",
  },
  {
    id: "rate-cut",
    hotLabel: "熱門",
    category: "宏觀",
    title: "聯準會在下一次會議前是否會釋出更明確的降息訊號?",
    yes: 18,
    no: 82,
    yesBarClass: "w-[180px]",
    noBarClass: "flex-1",
    volume: "$3.1M",
    traders: "6.7k",
    resolution: "週五 20:00",
    imageUrl:
      "https://images.unsplash.com/photo-1763749531202-fb75f6a85845?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzQyNTA4OTh8&ixlib=rb-4.1.0&q=80&w=1080",
  },
  {
    id: "enterprise-ai",
    hotLabel: "熱門",
    category: "科技",
    title: "下一季企業 AI 支出年增率是否會超過 25%?",
    yes: 27,
    no: 73,
    yesBarClass: "w-[250px]",
    noBarClass: "flex-1",
    volume: "$2.6M",
    traders: "5.1k",
    resolution: "本季財報週",
    imageUrl:
      "https://images.unsplash.com/photo-1667964267136-c0256d70b7a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzQzMjQzMDN8&ixlib=rb-4.1.0&q=80&w=1080",
  },
];

export const PREDICTION_CARDS = [
  {
    title: "G 党會在 2028 年贏得美國總統大選嗎?",
    category: "政治",
    yes: 51,
    no: 49,
    yesWidthClass: "w-[51%]",
    noWidthClass: "w-[49%]",
    volume: "16.1K FP",
    time: "963d 10h",
    avatarUrl:
      "https://images.unsplash.com/photo-1667964267136-c0256d70b7a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzQzMjQzMDN8&ixlib=rb-4.1.0&q=80&w=200",
  },
  {
    title: "OpenAI 下一輪融資估值是否突破 5000 億美元?",
    category: "科技",
    yes: 51,
    no: 49,
    yesWidthClass: "w-[51%]",
    noWidthClass: "w-[49%]",
    volume: "9.8K FP",
    time: "247d 3h",
    avatarUrl:
      "https://images.unsplash.com/photo-1759485970442-3eea6cbc503d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzQzMjQzMDV8&ixlib=rb-4.1.0&q=80&w=200",
  },
  {
    title: "BTC 本週是否會重新站上 90,000 美元?",
    category: "金融",
    yes: 51,
    no: 49,
    yesWidthClass: "w-[51%]",
    noWidthClass: "w-[49%]",
    volume: "8.2K FP",
    time: "389d 8h",
    avatarUrl:
      "https://images.unsplash.com/photo-1586449480523-8db040d36c0f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzQzMjQzMDZ8&ixlib=rb-4.1.0&q=80&w=200",
  },
  {
    title: "勇士隊能否在季後賽首輪拿下主場優勢?",
    category: "體育",
    yes: 53,
    no: 47,
    yesWidthClass: "w-[53%]",
    noWidthClass: "w-[47%]",
    volume: "7.6K FP",
    time: "644d 10h",
    avatarUrl:
      "https://images.unsplash.com/photo-1611581719398-08fe2eb020c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzQzMjQzMDh8&ixlib=rb-4.1.0&q=80&w=200",
  },
  {
    title: "美國 10 年期殖利率月底前是否低於 4.1%?",
    category: "宏觀",
    yes: 53,
    no: 47,
    yesWidthClass: "w-[53%]",
    noWidthClass: "w-[47%]",
    volume: "11.4K FP",
    time: "236d 10h",
    avatarUrl:
      "https://images.unsplash.com/photo-1755052183867-a777a30fe035?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzQzMjQzMDR8&ixlib=rb-4.1.0&q=80&w=200",
  },
  {
    title: "台灣 AI 伺服器出口下半年是否續創新高?",
    category: "台灣",
    yes: 51,
    no: 49,
    yesWidthClass: "w-[51%]",
    noWidthClass: "w-[49%]",
    volume: "9.1K FP",
    time: "1200d 10h",
    avatarUrl:
      "https://images.unsplash.com/photo-1773841915558-25083446c52e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzQzMjQzMDV8&ixlib=rb-4.1.0&q=80&w=200",
  },
  {
    title: "下一代 iPhone 是否會導入更高階的 on-device AI?",
    category: "硬體",
    yes: 51,
    no: 49,
    yesWidthClass: "w-[51%]",
    noWidthClass: "w-[49%]",
    volume: "12.8K FP",
    time: "351d 9h",
    avatarUrl:
      "https://images.unsplash.com/photo-1614728729684-c1b01635aa26?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzQzMjQzMDd8&ixlib=rb-4.1.0&q=80&w=200",
  },
  {
    title: "NBA 總冠軍熱門球隊是否會在交易截止後改變?",
    category: "體育",
    yes: 51,
    no: 49,
    yesWidthClass: "w-[51%]",
    noWidthClass: "w-[49%]",
    volume: "9.7K FP",
    time: "716d 8h",
    avatarUrl:
      "https://images.unsplash.com/photo-1742805382149-3c2f0cd0f300?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzQzMjQzMDh8&ixlib=rb-4.1.0&q=80&w=200",
  },
];
